#!/usr/local/bin/node

let request = require("request");
let Phrase = require("platypus-palindrome");

let url = 'https://cdn.learnenough.com/phrases.txt'

request(url, function(error, response, body) {
  let lines = body.split("\n");
  let palindromes = lines.filter( function(line) {
    let phrase = new Phrase(line);
    return phrase.palindrome();
  });

  palindromes.forEach(function (palindrome) {
    console.log("palindrome detected: ", palindrome);
  });
});
